
const script = `
-- CREAR BASE DE DATOS

CREATE SCHEMA IF NOT EXISTS TSE;

--  TABLA CIUDADANO

CREATE TABLE IF NOT EXISTS TSE.CIUDADANO (
  dpi VARCHAR(13)  NOT NULL,
  nombre VARCHAR(50) NOT NULL,
  apellido VARCHAR(50) NOT NULL,
  edad INT NOT NULL,
  genero CHAR(1) NOT NULL,
  direccion VARCHAR(100) NOT NULL,
  telefono VARCHAR(10) NOT NULL,
  PRIMARY KEY (dpi));

-- TABLA DEPARTAMENTO

CREATE TABLE IF NOT EXISTS TSE.DEPARTAMENTO (
  id_dep INTEGER NOT NULL PRIMARY KEY ,
  nombre VARCHAR(25) NOT NULL
);


-- TABLA CARGO

CREATE TABLE IF NOT EXISTS TSE.CARGO (
    id_cargo INTEGER NOT NULL PRIMARY KEY,
    cargo VARCHAR(100) NOT NULL
);


-- TABLA PARTIDO

CREATE TABLE IF NOT EXISTS TSE.PARTIDO (
  id_partido INTEGER NOT NULL PRIMARY KEY,
  nombre VARCHAR(50) NOT NULL,
  siglas VARCHAR(50) NOT NULL,
  fundacion DATE NOT NULL
);

-- TABLA MESA

CREATE TABLE IF NOT EXISTS TSE.MESA (
  id_mesa INTEGER NOT NULL PRIMARY KEY,
  id_dep INTEGER NOT NULL,
  CONSTRAINT FK_depto FOREIGN KEY (id_dep) REFERENCES TSE.DEPARTAMENTO(id_dep)
);

-- TABLA CANDIDATO

CREATE TABLE IF NOT EXISTS TSE.CANDIDATO (
  id_candidato INTEGER NOT NULL PRIMARY KEY,
  nombre VARCHAR(50) NOT NULL,
  fecha_nac DATE NOT NULL,
  id_cargo INTEGER NOT NULL,
  id_partido INTEGER NOT NULL,
  CONSTRAINT FK_cargo FOREIGN KEY (id_cargo) REFERENCES TSE.CARGO(id_cargo),
  CONSTRAINT FK_partido FOREIGN KEY (id_partido) REFERENCES TSE.PARTIDO(id_partido)

);


-- TABLA VOTO

CREATE TABLE IF NOT EXISTS TSE.VOTO (
  idvoto INTEGER NOT NULL PRIMARY KEY,
  fechahora DATETIME NOT NULL,
  dpi VARCHAR(13) NOT NULL,
  id_mesa INTEGER NOT NULL,
  CONSTRAINT FK_ciudadano FOREIGN KEY (dpi) REFERENCES TSE.CIUDADANO (dpi),
  CONSTRAINT FK_mesa FOREIGN KEY (id_mesa) REFERENCES TSE.MESA (id_mesa)
);


-- TABLA DETALLE VOTO

CREATE TABLE IF NOT EXISTS TSE.DETALLE_VOTO (
  id_detalle INTEGER AUTO_INCREMENT  PRIMARY KEY,
  idvoto INTEGER NOT NULL,
  id_candidato INTEGER NOT NULL,
  CONSTRAINT FK_idvoto FOREIGN KEY (idvoto) REFERENCES TSE.VOTO (idvoto),
  CONSTRAINT FK_candi FOREIGN KEY (id_candidato) REFERENCES TSE.CANDIDATO (id_candidato)
);

`;

module.exports = script;



